/*
 * Class: CMSC203 
 * Instructor: Professor Khandan Monshi
 * Description: a program that receives a guess from the user and check if the guess is the random number that was generated.  
 * 					The program will narrow down the choices according to the user's previous guesses
 * 					and continue to prompt you to enter a guess until you guess correctly.  
 * Due: 2/23/2021
 * Platform/compiler: Eclipse
 * I pledge that I have completed the programming assignment independently.
   I have not copied the code from a student or any source.
   I have not given my code to any student.
   Print your Name here: Abdullah Shamsan
*/

/**
 * @author AShamsan 
 * 
 */
import java.util.Scanner;

public class RandomNumberGuesser {
	
	public static void main(String[] args) {
		
		// Define a constant string holding my name
		final String programmerName = "Abdullah Shamsan";
		
		// Create a new scanner named userInput to get the user's guesses and choice to continue playing
		Scanner userInput = new Scanner (System.in);
		
		// Define a string named userChoice to hold the user choice whether to continue playing or not
		String userChoice;
		
		// Define integer variables to be the range of lowest and highest numbers 
		//	that the user should enter a number between
		int lowGuess,  highGuess;
		
		// Define integer variable to hold the user's guess
		int nextGuess; 
		
		
		
		// Start the do-while loop (the loop will start again if the user chose to continue playing)
		do {
			// Call resetCount method from RNG.java to set the number of guesses to 0
			RNG.resetCount();
			
			// Define an integer variable and initialize it to hold the random number generated by the program in RNG.java
			int randNum = RNG.rand();
			
			// Set the range of numbers initially to be between 0 and 100
			// each time the loop is repeated the range will be set to 0 and 100
			lowGuess = 0;
			highGuess = 100; 
			
			// Print a header of the program
			System.out.println("== Random Number Guesser ========");
			
			// Promote the user to enter the first guess
			System.out.println("Enter your first guess");
			
			// Initialize the variable nextGuess with the user's first guess
			nextGuess = userInput.nextInt();
			
			// Start a while loop that will keep running until the user's input is correct
			while(!(nextGuess == randNum)) 
			{
				
				// The program will display the number of the guesses  to the user 
				System.out.println("Number of guesses is " +(RNG.getCount()+1));
				
					// This if statement will run if the user's input is higher than the random number generated
					//  and will set the variable highGuess to be equal to the user's input
					if (nextGuess > randNum && nextGuess < highGuess) 
					{
					
						// Program will display a message telling the user his guess is higher than the random number
						System.out.println("Your guess is too high");
						
						// variable highGuess will be set to be the user's guess
						highGuess = nextGuess;
					} 
				
					// This else-if statement will run if the user's input is lower than the random number generated
					//  and will set the variable lowGuess to be equal to the user's input
					else if (nextGuess < randNum && nextGuess > lowGuess) 
					{
						
						// Program will display a message telling the user his guess is lower than the random number
						System.out.println("Your guess is too low");
						
						// variable lowGuess will be set to be the user's guess
						lowGuess = nextGuess;
					}
				
					
					// call inputValidation method from RNG.java to check if the user's guess
					// is in the range between lowGuess and highGuess and to increment count by 1
					RNG.inputValidation(nextGuess, lowGuess, highGuess);
					
				
					// Initialize the variable nextGuess with the user's next guess
					nextGuess = userInput.nextInt();
			}
			// end of the while loop

			// If the user's first guess is correct the program will display the number of guesses
			// a message to congratulate the user and will ask if the user want to play again
			System.out.println("Number of guesses is " +(RNG.getCount()+ 1));
			System.out.println("Congratulations, you guessed correctly\n"
					+ "Try again? (yes or no)");
			
			// the user choice will be saved into userChoice
			userChoice = userInput.next();
			
			if(userChoice.equalsIgnoreCase("YES")) 
			{
				System.out.println("\n");
			}
			
			
			// The loop will repeat if the user choice was yes
		} while (userChoice.equalsIgnoreCase("YES"));
		// end of the do-while loop
		
		// Program will display a message to thank the user for playing
		System.out.println("Thanks for playing...\n\n");
		
		// Close the scanner userInput
		userInput.close();
		
		// Display the user's name (my name)
		System.out.println("Programmer name: " + programmerName);
	}	
}